# Generated by Django 4.2.4 on 2023-09-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0006_advert_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='user',
        ),
    ]
