# Generated by Django 4.2.4 on 2023-09-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advert', '0007_remove_advert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default='', upload_to='advert/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
